import type { Feature, FeatureCollection } from 'geojson';
import type { Topology, GeometryCollection } from 'topojson-specification';
import { useState, useEffect } from 'react';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import MapControls from './MapControls.js';

// Both files are generated by scripts/generate-pizza-data.py and served from
// /images/pizza/* — root-relative on purpose, so they resolve through the
// tylerbarron.com CloudFront distribution (compressed at the edge) and stay
// same-origin, which fetch() needs since the bucket sends no CORS headers.
// Same reasoning as TrophyModel.tsx.
const LOCATIONS_URL = '/images/pizza/dominos-locations.json';
const NETWORK_URL = '/images/pizza/pizza-network.json';

type LocationData = {
  latitude: number;
  longitude: number;
  rating: number;
  total_ratings: number;
  state: string;
}

type PizzaScoreData = {
  latitude: number;
  longitude: number;
  pizza_score: number;
  /** Domino's within the smoothing radius — how much this cell rests on. */
  stores: number;
  reviews: number;
}

export default function PizzaLocationMap() {
  const [reviewData, setReviewData] = useState<LocationData[]>([]);
  const [scoreData, setScoreData] = useState<PizzaScoreData[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [hoveredLocation, setHoveredLocation] = useState<LocationData | null>(null);
  const [hoveredScore, setHoveredScore] = useState<PizzaScoreData | null>(null);
  const [showReviews, setShowReviews] = useState<boolean>(false);
  const [showPizzaScore, setShowPizzaScore] = useState<boolean>(true);
  const [showPerfectRatings, setShowPerfectRatings] = useState<boolean>(false);
  const [usStates, setUsStates] = useState<FeatureCollection | null>(null);
  const [scoreFilter, setScoreFilter] = useState(0);


  // Constants
  const width = 1200;
  const height = 800;
  const projection = geoAlbersUsa()
    .scale(1400)
    .translate([width / 2, height / 2]);

  // Fetch US States data
  useEffect(() => {
    const fetchStates = async () => {
      try {
        const response = await fetch('https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json');
        const topology = await response.json() as Topology<{ states: GeometryCollection }>;
        setUsStates(feature(topology, topology.objects.states));
      } catch (error) {
        console.error('Error loading US states:', error);
      }
    };
    fetchStates();
  }, []);

  // Fetch review data
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        const response = await fetch(LOCATIONS_URL);
        const locations = await response.json() as LocationData[];
        setReviewData(locations);
        setLoading(false);
      } catch (error) {
        console.error('Error loading data:', error);
        setError('Failed to load location data');
        setLoading(false);
      }
    };

    loadData();
  }, []);

  // Fetch pizza score data
  useEffect(() => {
    const loadScoreData = async () => {
      try {
        const response = await fetch(NETWORK_URL);
        const scores = await response.json() as PizzaScoreData[];
        setScoreData(scores);
      } catch (error) {
        console.error('Error loading score data:', error);
      }
    };

    loadScoreData();
  }, []);

  // Calculate color based on rating
  const getRatingColor = (rating: number): string => {
    const hue = (rating / 5) * 120;
    return `hsl(${hue}, 70%, 50%)`;
  };

  // Render US states (excluding Alaska and Hawaii)
  const renderStates = () => {
    if (!usStates) return null;

    const pathGenerator = geoPath().projection(projection);

    return (
      <g className="states">
        {usStates.features
          .filter((feature: Feature) => {
            // Filter out Alaska (02) and Hawaii (15)
            const id = feature.id as string;
            return id !== "02" && id !== "15";
          })
          .map((feature: Feature, i: number) => (
            <path
              key={`state-${i}`}
              d={pathGenerator(feature) || undefined}
              fill="none"
              stroke="#333"
              strokeWidth="0.5"
            />
          ))}
      </g>
    );
  };

  // Render pizza score heatmap (continental US only)
  const renderPizzaScoreHeatmap = () => {
    if ((!showPizzaScore && !showPerfectRatings) || !scoreData.length) return null;
  
    return scoreData
      // The generator emits US-only cells, so no geographic filter here. The
      // one this replaced was a lat/lng box that also contains southern
      // Ontario, Quebec and New Brunswick — Canadian Domino's rate about half a
      // star higher, and since the score inverts, that used to render the
      // Buffalo/Niagara/Detroit corridor as the worst pizza in America.
      .filter(point => Number(point.pizza_score) >= scoreFilter)
      .map((point, i) => {
        const projected = projection([point.longitude, point.latitude]);
        if (!projected) return null;
        const [x, y] = projected;

        return (
          <circle
            key={`score-${i}`}
            cx={x}
            cy={y}
            r={6}
            fill={getRatingColor(point.pizza_score)}
            opacity={0.3}
            onMouseEnter={() => setHoveredScore(point)}
            onMouseLeave={() => setHoveredScore(null)}
            className="cursor-pointer"
          />
        );
      });
  };

  // Render review points (continental US only)
  const renderReviewPoints = () => {
    if (!showReviews || !reviewData.length) return null;

    // US-only by construction — see the note in renderPizzaScoreHeatmap.
    return reviewData
      .map((location, i) => {
        const projected = projection([location.longitude, location.latitude]);
        if (!projected) return null;
        const [x, y] = projected;

        return (
          <circle
            key={`review-${i}`}
            cx={x}
            cy={y}
            r={4}
            fill={showPerfectRatings ? '#00ff00' : getRatingColor(location.rating)}
            opacity={0.8}
            onMouseEnter={() => setHoveredLocation(location)}
            onMouseLeave={() => setHoveredLocation(null)}
            className="cursor-pointer"
          />
        );
      });
  };

  // Render hover information
  const renderHoverInfo = () => {
    if (hoveredLocation && showReviews) {
      const projected = projection([hoveredLocation.longitude, hoveredLocation.latitude]);
      if (!projected) return null;
      const [x, y] = projected;

      return (
        <g>
          <rect
            x={x + 10}
            y={y - 50}
            width={220}
            height={90}
            fill="white"
            stroke="#333"
            strokeWidth="1"
            rx={4}
            opacity={0.95}
          />
          <text x={x + 20} y={y - 25} fontSize={14} fontWeight="600" fill="#333">
            Domino&apos;s Pizza ({hoveredLocation.state})
          </text>
          <text x={x + 20} y={y} fontSize={13} fill="#666">
            Rating: {hoveredLocation.rating.toFixed(1)} ★
          </text>
          <text x={x + 20} y={y + 25} fontSize={13} fill="#666">
            Reviews: {hoveredLocation.total_ratings.toLocaleString()}
          </text>
        </g>
      );
    }

    if (hoveredScore && (showPizzaScore || showPerfectRatings) && !showReviews) {
      const projected = projection([hoveredScore.longitude, hoveredScore.latitude]);
      if (!projected) return null;
      const [x, y] = projected;

      return (
        <g>
          <rect
            x={x + 10}
            y={y - 40}
            width={200}
            height={70}
            fill="white"
            stroke="#333"
            strokeWidth="1"
            rx={4}
            opacity={0.95}
          />
          <text x={x + 20} y={y - 15} fontSize={14} fontWeight="600" fill="#333">
            Pizza Score {hoveredScore.pizza_score.toFixed(2)}
          </text>
          <text x={x + 20} y={y + 10} fontSize={13} fill="#666">
            {hoveredScore.stores} shops · {hoveredScore.reviews.toLocaleString()} reviews
          </text>
        </g>
      );
    }

    return null;
  };

  if (loading) {
    return (
      <div className="w-full bg-white border-4 border-black p-8 text-center mt-4">
        <p className="font-neo font-bold text-black uppercase tracking-widest animate-pulse">Loading location data…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="w-full bg-white border-4 border-red-600 p-6 mt-4">
        <p className="font-neo font-bold text-red-600 uppercase mb-2 tracking-widest">Failed to Load Map</p>
        <p className="font-neo text-red-600 font-bold text-sm uppercase">{error}</p>
      </div>
    );
  }

  return (
    <div className="w-full h-full bg-white border-4 border-black mt-4">
      <div className="p-4 md:p-6">
      <MapControls
  showReviews={showReviews}
  setShowReviews={setShowReviews}
  setShowPizzaScore={setShowPizzaScore}
  setShowPerfectRatings={setShowPerfectRatings}
  scoreFilter={scoreFilter}
  setScoreFilter={setScoreFilter}
/>

        <div className="h-[50vh] max-h-[800px] relative bg-white border-4 border-black overflow-hidden">
          <svg
            width="100%"
            height="100%"
            viewBox={`0 0 ${width} ${height}`}
            preserveAspectRatio="xMidYMid meet"
          >
            <rect width={width} height={height} fill="#f5f5f5" />
            {renderStates()}
            {renderPizzaScoreHeatmap()}
            {renderReviewPoints()}
            {renderHoverInfo()}
          </svg>
        </div>

        <div className="mt-8 grid gap-8 border-t-4 border-black pt-6">
          <div>
            <div className="text-xl font-black font-neo uppercase tracking-tighter text-black mb-3">Background</div>
            <div className="text-sm md:text-base font-neo font-medium text-black space-y-2">
              <div>This map reveals America's best pizza regions through Domino's Pizza ratings.</div>
              <div>The methodology builds on three assumptions:</div>
              <div className="pl-4">1. Domino's pizza is Domino's pizza. It is highly standardized nationwide, making it a reliable control variable.</div>
              <div className="pl-4">2. Pizza shop employees are constant enough that they impact the ratings in a standardized way.</div>
              <div className="pl-4 pb-2">3. As a result of (1) and (2), the differentiating factor for the reviews is not the pizza but the competitors in the area. The better the local pizza is, the worse Domino's will be rated.</div>
              <div className="pb-2">My Pizza Score inverts Domino's Google Maps ratings: lower Domino's ratings suggest higher-quality local pizza alternatives. This creates a proxy measure for regional pizza - areas where Domino's struggles are areas where local pizzerias are best.</div>
            </div>
            <div className="mt-8">
              <div className="text-xl font-black font-neo uppercase tracking-tighter text-black mb-4">Statistics</div>
              <div className="text-sm md:text-base font-neo font-medium text-black space-y-3">
                <div className="flex justify-between border-b-2 border-black/10 pb-1">
                  <span className="uppercase font-bold tracking-widest opacity-60 text-[10px] md:text-xs">Total Locations Sampled</span>
                  <span className="font-black text-lg md:text-xl tracking-tighter">{reviewData.length.toLocaleString()}</span>
                </div>
                <div className="flex justify-between border-b-2 border-black/10 pb-1">
                  <span className="uppercase font-bold tracking-widest opacity-60 text-[10px] md:text-xs">Average Rating</span>
                  <span className="font-black text-lg md:text-xl tracking-tighter">
                  {(reviewData.reduce((sum, loc) => sum + loc.rating, 0) / reviewData.length).toFixed(2)}
                  </span>
                </div>
                <div className="flex justify-between border-b-2 border-black/10 pb-1">
                  <span className="uppercase font-bold tracking-widest opacity-60 text-[10px] md:text-xs">Total Reviews</span>
                  <span className="font-black text-lg md:text-xl tracking-tighter">
                  {reviewData.reduce((sum, loc) => sum + loc.total_ratings, 0).toLocaleString()}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}