import type { Feature, FeatureCollection } from 'geojson';
import type { Topology, GeometryCollection } from 'topojson-specification';
import { useState, useEffect } from 'react';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import MapControls from './MapControls.js';

// Both files are generated by scripts/generate-pizza-data.py and served from
// /images/pizza/* — root-relative on purpose, so they resolve through the
// tylerbarron.com CloudFront distribution (compressed at the edge) and stay
// same-origin, which fetch() needs since the bucket sends no CORS headers.
// Same reasoning as TrophyModel.tsx.
const LOCATIONS_URL = '/images/pizza/dominos-locations.json';
const NETWORK_URL = '/images/pizza/pizza-network.json';

// Two scales, because the layers encode different things and must not share a
// ramp. The Pizza Score is a percentile centred on the national median, so it
// is *diverging* — above/below typical, neutral in the middle. A raw star
// rating is magnitude, so it is *sequential* — one hue, light to dark.
//
// Both replace an `hsl(rating/5 * 120, 70%, 50%)` red→yellow→green sweep. That
// ramp measured CVD ΔE 3.7 between its midpoint and its top end (protanopia,
// OKLab ×100) against a target of 8 — i.e. for a red-green colourblind reader,
// "average" and "best" were nearly the same colour. Blue↔red measures 12.9 on
// the same test, and every step below clears 3:1 against the #f5f5f5 map
// surface. Don't reintroduce a hue sweep here.
type Stop = { at: number; hex: string };

/** Diverging. Blue = Domino's rates well (weaker local pizza); red = the reverse. */
const SCORE_RAMP: Stop[] = [
  { at: 0, hex: '#1c5cab' },
  { at: 1.25, hex: '#3987e5' },
  { at: 2.5, hex: '#e9e7e2' },  // neutral: at the median, deliberately recessive
  { at: 3.75, hex: '#d03b3b' },
  { at: 5, hex: '#8f1f1f' },
];

/**
 * Sequential, single hue. Domain is 3.0–4.5 stars with clamping, not 0–5:
 * real ratings span 1.7–4.9 but bunch between 3.4 and 4.2, so a full 0–5 domain
 * renders the whole country one flat shade. The legend states the domain.
 */
const RATING_RAMP: Stop[] = [
  { at: 3.0, hex: '#86b6ef' },
  { at: 3.5, hex: '#3987e5' },
  { at: 4.0, hex: '#1c5cab' },
  { at: 4.5, hex: '#0d366b' },
];

/**
 * The legend bar, drawn from the same stops the map uses so the two can't
 * drift apart. SVG rather than a CSS gradient because the repo forbids inline
 * `style` props (react/forbid-dom-props) and Tailwind can't see arbitrary
 * colours built at runtime.
 */
function RampBar({ stops, id }: { stops: Stop[]; id: string }) {
  const lo = stops[0].at;
  const span = stops[stops.length - 1].at - lo;
  return (
    <svg
      className="w-full h-4 border-2 border-black block"
      preserveAspectRatio="none"
      viewBox="0 0 100 10"
      // Decorative: the endpoint captions beside it carry the meaning.
      aria-hidden="true"
    >
      <defs>
        <linearGradient id={id} x1="0" x2="1" y1="0" y2="0">
          {stops.map(s => (
            <stop key={s.at} offset={`${(((s.at - lo) / span) * 100).toFixed(1)}%`} stopColor={s.hex} />
          ))}
        </linearGradient>
      </defs>
      <rect width="100" height="10" fill={`url(#${id})`} />
    </svg>
  );
}

function rampColor(stops: Stop[], value: number): string {
  const first = stops[0];
  const last = stops[stops.length - 1];
  if (!(value > first.at)) return first.hex;
  if (value >= last.at) return last.hex;

  const upper = stops.findIndex(s => s.at > value);
  const lo = stops[upper - 1];
  const hi = stops[upper];
  const t = (value - lo.at) / (hi.at - lo.at);

  const channel = (hex: string, i: number) => parseInt(hex.slice(1 + i * 2, 3 + i * 2), 16);
  const mix = (i: number) => Math.round(channel(lo.hex, i) + (channel(hi.hex, i) - channel(lo.hex, i)) * t);
  return `#${[0, 1, 2].map(i => mix(i).toString(16).padStart(2, '0')).join('')}`;
}

type LocationData = {
  latitude: number;
  longitude: number;
  rating: number;
  total_ratings: number;
  state: string;
}

type PizzaScoreData = {
  latitude: number;
  longitude: number;
  pizza_score: number;
  /** Domino's within the smoothing radius — how much this cell rests on. */
  stores: number;
  reviews: number;
}

export default function PizzaLocationMap() {
  const [reviewData, setReviewData] = useState<LocationData[]>([]);
  const [scoreData, setScoreData] = useState<PizzaScoreData[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [hoveredLocation, setHoveredLocation] = useState<LocationData | null>(null);
  const [hoveredScore, setHoveredScore] = useState<PizzaScoreData | null>(null);
  const [showReviews, setShowReviews] = useState<boolean>(false);
  const [showPizzaScore, setShowPizzaScore] = useState<boolean>(true);
  const [usStates, setUsStates] = useState<FeatureCollection | null>(null);
  const [scoreFilter, setScoreFilter] = useState(0);


  // Constants
  const width = 1200;
  const height = 800;
  const projection = geoAlbersUsa()
    .scale(1400)
    .translate([width / 2, height / 2]);

  // Fetch US States data
  useEffect(() => {
    const fetchStates = async () => {
      try {
        const response = await fetch('https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json');
        const topology = await response.json() as Topology<{ states: GeometryCollection }>;
        setUsStates(feature(topology, topology.objects.states));
      } catch (error) {
        console.error('Error loading US states:', error);
      }
    };
    fetchStates();
  }, []);

  // Fetch review data
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        const response = await fetch(LOCATIONS_URL);
        const locations = await response.json() as LocationData[];
        setReviewData(locations);
        setLoading(false);
      } catch (error) {
        console.error('Error loading data:', error);
        setError('Failed to load location data');
        setLoading(false);
      }
    };

    loadData();
  }, []);

  // Fetch pizza score data
  useEffect(() => {
    const loadScoreData = async () => {
      try {
        const response = await fetch(NETWORK_URL);
        const scores = await response.json() as PizzaScoreData[];
        setScoreData(scores);
      } catch (error) {
        console.error('Error loading score data:', error);
      }
    };

    loadScoreData();
  }, []);

  const getScoreColor = (score: number): string => rampColor(SCORE_RAMP, score);
  const getRatingColor = (rating: number): string => rampColor(RATING_RAMP, rating);

  // Render US states (excluding Alaska and Hawaii)
  const renderStates = () => {
    if (!usStates) return null;

    const pathGenerator = geoPath().projection(projection);

    return (
      <g className="states">
        {usStates.features
          .filter((feature: Feature) => {
            // Filter out Alaska (02) and Hawaii (15)
            const id = feature.id as string;
            return id !== "02" && id !== "15";
          })
          .map((feature: Feature, i: number) => (
            <path
              key={`state-${i}`}
              d={pathGenerator(feature) || undefined}
              fill="none"
              stroke="#333"
              strokeWidth="0.5"
            />
          ))}
      </g>
    );
  };

  // Render pizza score heatmap (continental US only)
  const renderPizzaScoreHeatmap = () => {
    if (!showPizzaScore || !scoreData.length) return null;
  
    return scoreData
      // No geographic filter: the one this replaced was a lat/lng box that also
      // contains southern Ontario, Quebec and New Brunswick, and Canadian
      // Domino's rate about half a star higher — since the score inverts, that
      // rendered the Buffalo/Niagara/Detroit corridor as the worst pizza in
      // America. The generator now filters *stores* to US states, which fixes
      // the scores. It does not mask the grid, though: cells are emitted
      // wherever 3+ US stores fall within the smoothing radius, so a handful
      // still land over Lake Ontario and the Gulf. Cosmetic, not a data bug.
      .filter(point => Number(point.pizza_score) >= scoreFilter)
      .map((point, i) => {
        const projected = projection([point.longitude, point.latitude]);
        if (!projected) return null;
        const [x, y] = projected;

        return (
          <circle
            key={`score-${i}`}
            cx={x}
            cy={y}
            r={5.5}
            fill={getScoreColor(point.pizza_score)}
            // Cells nearly tile at this radius, so heavy transparency is no
            // longer needed to see the map beneath — and overlapping alpha was
            // compounding into false intensity where the grid is dense.
            opacity={0.9}
            onMouseEnter={() => setHoveredScore(point)}
            onMouseLeave={() => setHoveredScore(null)}
            className="cursor-pointer"
          />
        );
      });
  };

  // Render review points (continental US only)
  const renderReviewPoints = () => {
    if (!showReviews || !reviewData.length) return null;

    // US-only by construction — see the note in renderPizzaScoreHeatmap.
    return reviewData
      .map((location, i) => {
        const projected = projection([location.longitude, location.latitude]);
        if (!projected) return null;
        const [x, y] = projected;

        return (
          <circle
            key={`review-${i}`}
            cx={x}
            cy={y}
            r={4}
            fill={getRatingColor(location.rating)}
            opacity={0.85}
            onMouseEnter={() => setHoveredLocation(location)}
            onMouseLeave={() => setHoveredLocation(null)}
            className="cursor-pointer"
          />
        );
      });
  };

  // Render hover information
  const renderHoverInfo = () => {
    if (hoveredLocation && showReviews) {
      const projected = projection([hoveredLocation.longitude, hoveredLocation.latitude]);
      if (!projected) return null;
      const [x, y] = projected;

      return (
        <g>
          <rect
            x={x + 10}
            y={y - 50}
            width={220}
            height={90}
            fill="white"
            stroke="#333"
            strokeWidth="1"
            rx={4}
            opacity={0.95}
          />
          <text x={x + 20} y={y - 25} fontSize={14} fontWeight="600" fill="#333">
            Domino&apos;s Pizza ({hoveredLocation.state})
          </text>
          <text x={x + 20} y={y} fontSize={13} fill="#666">
            Rating: {hoveredLocation.rating.toFixed(1)} ★
          </text>
          <text x={x + 20} y={y + 25} fontSize={13} fill="#666">
            Reviews: {hoveredLocation.total_ratings.toLocaleString()}
          </text>
        </g>
      );
    }

    if (hoveredScore && showPizzaScore && !showReviews) {
      const projected = projection([hoveredScore.longitude, hoveredScore.latitude]);
      if (!projected) return null;
      const [x, y] = projected;

      return (
        <g>
          <rect
            x={x + 10}
            y={y - 40}
            width={200}
            height={70}
            fill="white"
            stroke="#333"
            strokeWidth="1"
            rx={4}
            opacity={0.95}
          />
          <text x={x + 20} y={y - 15} fontSize={14} fontWeight="600" fill="#333">
            Pizza Score {hoveredScore.pizza_score.toFixed(2)}
          </text>
          <text x={x + 20} y={y + 10} fontSize={13} fill="#666">
            {hoveredScore.stores} shops · {hoveredScore.reviews.toLocaleString()} reviews
          </text>
        </g>
      );
    }

    return null;
  };

  if (loading) {
    return (
      <div className="w-full bg-white border-4 border-black p-8 text-center mt-4">
        <p className="font-neo font-bold text-black uppercase tracking-widest animate-pulse">Loading location data…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="w-full bg-white border-4 border-red-600 p-6 mt-4">
        <p className="font-neo font-bold text-red-600 uppercase mb-2 tracking-widest">Failed to Load Map</p>
        <p className="font-neo text-red-600 font-bold text-sm uppercase">{error}</p>
      </div>
    );
  }

  return (
    <div className="w-full h-full bg-white border-4 border-black mt-4">
      <div className="p-4 md:p-6">
      <MapControls
  showReviews={showReviews}
  setShowReviews={setShowReviews}
  setShowPizzaScore={setShowPizzaScore}
  scoreFilter={scoreFilter}
  setScoreFilter={setScoreFilter}
/>

        <div className="h-[50vh] max-h-[800px] relative bg-white border-4 border-black overflow-hidden">
          {/*
            role="img" + a summary label rather than per-mark focus handlers:
            the two layers are ~2,300 grid cells and ~5,700 store dots, so making
            each one tabbable would build an 8,000-stop tab trap — worse than the
            hover-only tooltips it set out to fix. The label carries the headline
            numbers; the Statistics block below carries the rest as real text.
          */}
          <svg
            width="100%"
            height="100%"
            viewBox={`0 0 ${width} ${height}`}
            preserveAspectRatio="xMidYMid meet"
            role="img"
            aria-label={
              showReviews
                ? `Map of ${reviewData.length.toLocaleString()} US Domino's locations, shaded by Google rating from 3.0 stars or below (light blue) to 4.5 or above (dark blue).`
                : `Map of the United States shaded by Pizza Score across ${scoreData.length.toLocaleString()} grid cells. Blue marks areas where Domino's rates well, red where it rates poorly — read as a percentile against the national median, not a star rating.`
            }
          >
            <rect width={width} height={height} fill="#f5f5f5" />
            {renderStates()}
            {renderPizzaScoreHeatmap()}
            {renderReviewPoints()}
            {renderHoverInfo()}
          </svg>
        </div>

        <div className="mt-4 bg-white border-4 border-black p-4">
          {showReviews ? (
            <>
              <div className="font-neo font-extrabold uppercase tracking-widest text-black text-sm border-b-2 border-black pb-2 mb-3">
                Domino&apos;s Google Rating
              </div>
              <RampBar stops={RATING_RAMP} id="ratingRamp" />
              <div className="flex justify-between mt-1 font-neo font-bold text-[10px] md:text-xs uppercase tracking-widest text-black opacity-60">
                <span>3.0★ or below</span>
                <span>4.5★ or above</span>
              </div>
            </>
          ) : (
            <>
              <div className="font-neo font-extrabold uppercase tracking-widest text-black text-sm border-b-2 border-black pb-2 mb-3">
                Pizza Score
              </div>
              <RampBar stops={SCORE_RAMP} id="scoreRamp" />
              <div className="flex justify-between mt-1 font-neo font-bold text-[10px] md:text-xs uppercase tracking-widest text-black opacity-60">
                <span>Domino&apos;s rates well</span>
                <span>Typical</span>
                <span>Domino&apos;s rates poorly</span>
              </div>
              <div className="mt-3 font-neo font-medium text-xs md:text-sm text-black">
                A percentile, not a star rating: it ranks each area against the national median. The full sweep covers well under half a star of real variation.
              </div>
            </>
          )}
        </div>

        <div className="mt-8 grid gap-8 border-t-4 border-black pt-6">
          <div>
            <div className="text-xl font-black font-neo uppercase tracking-tighter text-black mb-3">Background</div>
            <div className="text-sm md:text-base font-neo font-medium text-black space-y-2">
              <div>This map reveals America's best pizza regions through Domino's Pizza ratings.</div>
              <div>The methodology builds on three assumptions:</div>
              <div className="pl-4">1. Domino's pizza is Domino's pizza. It is highly standardized nationwide, making it a reliable control variable.</div>
              <div className="pl-4">2. Pizza shop employees are constant enough that they impact the ratings in a standardized way.</div>
              <div className="pl-4 pb-2">3. As a result of (1) and (2), the differentiating factor for the reviews is not the pizza but the competitors in the area. The better the local pizza is, the worse Domino's will be rated.</div>
              <div className="pb-2">My Pizza Score inverts Domino's Google Maps ratings: lower Domino's ratings suggest higher-quality local pizza alternatives. This creates a proxy measure for regional pizza - areas where Domino's struggles are areas where local pizzerias are best.</div>
            </div>
            <div className="mt-8">
              <div className="text-xl font-black font-neo uppercase tracking-tighter text-black mb-4">Statistics</div>
              <div className="text-sm md:text-base font-neo font-medium text-black space-y-3">
                <div className="flex justify-between border-b-2 border-black/10 pb-1">
                  <span className="uppercase font-bold tracking-widest opacity-60 text-[10px] md:text-xs">Total Locations Sampled</span>
                  <span className="font-black text-lg md:text-xl tracking-tighter">{reviewData.length.toLocaleString()}</span>
                </div>
                <div className="flex justify-between border-b-2 border-black/10 pb-1">
                  <span className="uppercase font-bold tracking-widest opacity-60 text-[10px] md:text-xs">Average Rating</span>
                  <span className="font-black text-lg md:text-xl tracking-tighter">
                  {(reviewData.reduce((sum, loc) => sum + loc.rating, 0) / reviewData.length).toFixed(2)}
                  </span>
                </div>
                <div className="flex justify-between border-b-2 border-black/10 pb-1">
                  <span className="uppercase font-bold tracking-widest opacity-60 text-[10px] md:text-xs">Total Reviews</span>
                  <span className="font-black text-lg md:text-xl tracking-tighter">
                  {reviewData.reduce((sum, loc) => sum + loc.total_ratings, 0).toLocaleString()}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}