import type { MetaDescriptor } from "react-router";

export const SITE_URL = "https://tylerbarron.com";
export const SITE_NAME = "Barron Wasteland";
export const DEFAULT_DESCRIPTION =
  "The personal site of Tyler Barron — chess games, generative art, engineering projects, and writing.";

/** Default share card — generated by scripts/generate-og-image.py (1200x630). */
const DEFAULT_OG_IMAGE = "/images/og-default.png";
const DEFAULT_OG_IMAGE_DIMS = { width: 1200, height: 630 };

/** Resolve a possibly-relative image path to an absolute URL (required by OG/Twitter). */
function absoluteUrl(src: string): string {
  return /^https?:\/\//.test(src) ? src : `${SITE_URL}${src}`;
}

interface SeoArgs {
  title?: string;
  description?: string;
  /** Canonical path (e.g. "/chesser-guesser"). Emits og:url + a canonical link. */
  path?: string;
  type?: "website" | "article";
  /** Share-card image (absolute URL or site-relative path). Defaults to the brand card. */
  image?: string;
  /** Set on ephemeral pages (live games, 404s) to keep them out of search indexes. */
  noIndex?: boolean;
}

/**
 * Standard meta for a route: title, description, Open Graph, and Twitter card.
 * React Router only uses the leaf route's meta, so every indexable route
 * should call this rather than relying on root defaults.
 */
export function buildMeta({
  title,
  description = DEFAULT_DESCRIPTION,
  path,
  type = "website",
  image,
  noIndex = false,
}: SeoArgs = {}): MetaDescriptor[] {
  const fullTitle = title ? `${title} — ${SITE_NAME}` : SITE_NAME;
  const isDefaultImage = !image;
  const imageUrl = absoluteUrl(image ?? DEFAULT_OG_IMAGE);
  const meta: MetaDescriptor[] = [
    { title: fullTitle },
    { name: "description", content: description },
    { property: "og:title", content: fullTitle },
    { property: "og:description", content: description },
    { property: "og:type", content: type },
    { property: "og:site_name", content: SITE_NAME },
    { property: "og:image", content: imageUrl },
    { property: "og:image:alt", content: fullTitle },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:image", content: imageUrl },
  ];
  // Only the default card has known dimensions; custom images may differ.
  if (isDefaultImage) {
    meta.push(
      { property: "og:image:width", content: String(DEFAULT_OG_IMAGE_DIMS.width) },
      { property: "og:image:height", content: String(DEFAULT_OG_IMAGE_DIMS.height) },
    );
  }
  if (path) {
    const url = `${SITE_URL}${path}`;
    meta.push(
      { property: "og:url", content: url },
      { tagName: "link", rel: "canonical", href: url },
    );
  }
  if (noIndex) {
    meta.push({ name: "robots", content: "noindex" });
  }
  return meta;
}
