// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/boulderingTracker": {
    params: {};
  };
  "/camelUpCup": {
    params: {};
  };
  "/catTracker": {
    params: {};
  };
  "/catTracker/blog": {
    params: {};
  };
  "/chesserGuesser/unlimited": {
    params: {};
  };
  "/collaborativeCheckmate": {
    params: {};
  };
  "/collaborativeCheckmate/:gameId/:playerId": {
    params: {
      "gameId": string;
      "playerId": string;
    };
  };
  "/generativeArt": {
    params: {};
  };
  "/pizzaRating": {
    params: {};
  };
  "/set": {
    params: {};
  };
  "/SSBM": {
    params: {};
  };
  "/theRiddler": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog/:slug" | "/boulderingTracker" | "/camelUpCup" | "/catTracker" | "/catTracker/blog" | "/chesserGuesser/blog" | "/chesserGuesser/landing" | "/chesserGuesser/unlimited" | "/collaborativeCheckmate" | "/collaborativeCheckmate/:gameId/:playerId" | "/generativeArt" | "/pizzaRating" | "/set" | "/SSBM" | "/theRiddler";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/boulderingTracker.tsx": {
    id: "routes/boulderingTracker";
    page: "/boulderingTracker";
  };
  "routes/camelUpCup.tsx": {
    id: "routes/camelUpCup";
    page: "/camelUpCup";
  };
  "routes/catTracker._index.tsx": {
    id: "routes/catTracker._index";
    page: "/catTracker";
  };
  "routes/catTracker.blog.tsx": {
    id: "routes/catTracker.blog";
    page: "/catTracker/blog";
  };
  "routes/chesserGuesser.blog.tsx": {
    id: "routes/chesserGuesser.blog";
    page: "/chesserGuesser/blog";
  };
  "routes/chesserGuesser.landing.tsx": {
    id: "routes/chesserGuesser.landing";
    page: "/chesserGuesser/landing";
  };
  "routes/chesserGuesser.unlimited.tsx": {
    id: "routes/chesserGuesser.unlimited";
    page: "/chesserGuesser/unlimited";
  };
  "routes/collaborativeCheckmate._index.tsx": {
    id: "routes/collaborativeCheckmate._index";
    page: "/collaborativeCheckmate";
  };
  "routes/collaborativeCheckmate.$gameId.$playerId.tsx": {
    id: "routes/collaborativeCheckmate.$gameId.$playerId";
    page: "/collaborativeCheckmate/:gameId/:playerId";
  };
  "routes/generativeArt.tsx": {
    id: "routes/generativeArt";
    page: "/generativeArt";
  };
  "routes/pizzaRating.tsx": {
    id: "routes/pizzaRating";
    page: "/pizzaRating";
  };
  "routes/set.tsx": {
    id: "routes/set";
    page: "/set";
  };
  "routes/SSBM.tsx": {
    id: "routes/SSBM";
    page: "/SSBM";
  };
  "routes/theRiddler.tsx": {
    id: "routes/theRiddler";
    page: "/theRiddler";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/boulderingTracker": typeof import("./app/routes/boulderingTracker.tsx");
  "routes/camelUpCup": typeof import("./app/routes/camelUpCup.tsx");
  "routes/catTracker._index": typeof import("./app/routes/catTracker._index.tsx");
  "routes/catTracker.blog": typeof import("./app/routes/catTracker.blog.tsx");
  "routes/chesserGuesser.blog": typeof import("./app/routes/chesserGuesser.blog.tsx");
  "routes/chesserGuesser.landing": typeof import("./app/routes/chesserGuesser.landing.tsx");
  "routes/chesserGuesser.unlimited": typeof import("./app/routes/chesserGuesser.unlimited.tsx");
  "routes/collaborativeCheckmate._index": typeof import("./app/routes/collaborativeCheckmate._index.tsx");
  "routes/collaborativeCheckmate.$gameId.$playerId": typeof import("./app/routes/collaborativeCheckmate.$gameId.$playerId.tsx");
  "routes/generativeArt": typeof import("./app/routes/generativeArt.tsx");
  "routes/pizzaRating": typeof import("./app/routes/pizzaRating.tsx");
  "routes/set": typeof import("./app/routes/set.tsx");
  "routes/SSBM": typeof import("./app/routes/SSBM.tsx");
  "routes/theRiddler": typeof import("./app/routes/theRiddler.tsx");
};