// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../legacyRedirect.js")

type Info = GetInfo<{
  file: "routes/legacyRedirect.ts",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-bouldering-tracker";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-bouldering-tracker-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-camel-up-cup";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-camel-up-cup-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-cat-tracker";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-cat-tracker-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-cat-tracker-blog";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-cat-tracker-blog-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-chesser-guesser";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-collaborative-checkmate";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-collaborative-checkmate-game";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-generative-art";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-generative-art-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-pizza-rating";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-pizza-rating-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-the-riddler";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-the-riddler-pascal";
  module: typeof import("../legacyRedirect.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "legacy-set-pascal";
  module: typeof import("../legacyRedirect.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // ServerHydrateFallback
  export type ServerHydrateFallbackProps = Annotations["ServerHydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ServerComponent
  export type ServerComponentProps = Annotations["ServerComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];

  // ServerErrorBoundary
  export type ServerErrorBoundaryProps = Annotations["ServerErrorBoundaryProps"];
}