name: ⬣ Lint repository

on:
  push:
    branches:
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 22

      - name: 📥 Install deps
        run: npm install

      - name: 🔬 Lint
        run: npm run lint
